### ISSUE TITLE
Certain client scopes are not working at present, waiting on dev fix from Mixer team

### ISSUE THREAD

**Issue by SaviorXTanren** [SaviorXTanren/mixer-client-csharp#1]
Spoke with developers on Gitter and there is currently an issue with client scopes that focus on chat moderation. Until those are fixed, only a few basic pieces of the Chat Client functionality works.

> Hi @SaviorXTanren - the scopes listed on the developer site are accurate, but there is a known bug at the moment where the shortcode flow isn't accepting certain scopes that are usually reserved for chat moderators. We're working on it

**Comment by schuster19uk** [comment]
hi there, Do the scopes work for authorisation via other methods ?

**Comment by SaviorXTanren** [comment]
There's a bug in the Short Code authorization flow for Mixer where the moderator-focused scopes are not working (EX: Timeout, Delete Message, Clear Chat, etc). I have a work around for this presently that using the regular authorization flow instead of short codes, which does fix this issue. I have the fixes locally and expect to have them pushed up to the master branch in the next day or two. Once I do, I'll be closing this issue down.

**Comment by SaviorXTanren** [comment]
I've updated the master branch with the new fixes for using traditional OAuth authentication and added some method usage comments for short code authentication until the issue is fixed by the Mixer team. The samples included with the project detail how you can handle authentication via the traditional OAuth authentication.
