### ISSUE TITLE
How to update the game?

### ISSUE THREAD

**Issue by D3thw0lf** [SaviorXTanren/mixer-client-csharp#10]
I'm asking bc not finding any Code for it (yet) so I guessed it works the same like for StreamTitle

This is my Code
```c
        public async void UpdateStreamGameAsync(string game)
        {
            channel.type.name = game;
            await connection.Channels.UpdateChannel(channel);
        }
```

If this is not added yet maybe someone knows another good way to do this? I'm very "new" to push / update etc. Json stuff :3

**Comment by SaviorXTanren** [comment]
Hey, good question. it actually forced me to take a close look at the games type APIs and helped me to find a logic bug I had in there. :)

I have some sample code prepped for you, very easy to update. I'll post it up and send out an updated nuget package tonight when I get home.

**Comment by D3thw0lf** [comment]
Nice. Thanks a lot :)

**Comment by SaviorXTanren** [comment]
Ok, I just pushed up some changes to the master branch and updated the nuget package to 0.2.1-beta, which will have some of the fixes necessary for this. You can find a full unit test dedicated to this scenario in ChannelsServiceUnitTests.UpdateChannelGame(), but here's a snippet of the code below:

    ChannelModel channel = await connection.Channels.GetChannel(....);

    string gameName = "Fortnite";
    IEnumerable<GameTypeSimpleModel> games = await connection.GameTypes.GetGameTypes(gameName);

    channel.typeId = games.First().id;

    channel = await connection.Channels.UpdateChannel(channel);

**Comment by D3thw0lf** [comment]
Got it. Thanks a lot <3
