### ISSUE TITLE
Viewerlist / Chatters Endpoint

### ISSUE THREAD

**Issue by D3thw0lf** [SaviorXTanren/mixer-client-csharp#12]
It would be great if you could add that if we're connecting to the channels Chat all the currently chatters get grabbed, too. In the current Scenario if you're connecting all the chatters that are already there won't get added to the userlist (or I'm making something terrible wrong which I won't exclude).

Anyway if this is not a thing it would be great if you could make it some. :)

As always: Thanks for your great work ... srsly!

PS: "chat_view_lurkers" (scope) would ge a great addition, too ;)

**Comment by SaviorXTanren** [comment]
The scopes are not defined by me, they're defined by the Mixer team. So there isn't any scope related to lurkers.

If you want to get the users in chat, you need to do two things to get the users for chat:

- Call the ChatsService.GetUsers() API to get all currently connected users
- After connecting the ChatClient, subscribe to the OnUserJoinOccurred, OnUserLeaveOccurred, OnUserTimeoutOccurred, OnUserUpdateOccurred events to get user changes

**Comment by D3thw0lf** [comment]
API say's there's a scope like that and thanks for your fast answer. I'll try that out. :)

> Returns a paginated list of users in this channel's chatroom, includes lurkers if the user has the "chat:view_lurkers"

**Comment by SaviorXTanren** [comment]
I don't know if that scope exists or does anymore, as it's not on the scope list: https://dev.mixer.com/reference/oauth/index.html

I believe you'll just get lurkers all the time now when querying the API, but I would check with the Mixer team: https://gitter.im/Mixer/developers

**Comment by SaviorXTanren** [comment]
You can also get the latest Channel object down from the ChannelsService.GetChannel() and grab the viewersCurrent variable on there, which includes all lurkers.
