### ISSUE TITLE
Sample Clients missing

### ISSUE THREAD

**Issue by AlaskanDruid** [SaviorXTanren/mixer-client-csharp#16]
The documentation page states there are 2 sample clients created, and lots of unit tests.

Those are missing in the 0.4.0 (newest) beta.

**Comment by SaviorXTanren** [comment]
The unit tests and sample apps can't be included in the nuget package, it's just the Mixer.Base. If you want to run the unit tests and sample apps, you'll need to clone down the repository or you can look at the source code directly on GitHub if you just want to see what it looks like. Below are direct links to the unit tests and one of the sample apps. Let me know if you have any questions.

Unit Tests: https://github.com/SaviorXTanren/mixer-client-csharp/tree/master/Mixer.UnitTests

Chat Sample: https://github.com/SaviorXTanren/mixer-client-csharp/tree/master/Mixer.ChatSample
