### ISSUE TITLE
OnUserTimeoutOccurred event does not seem to fire.

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/mixer-client-csharp#19]
I was looking to use the OnUserTimeoutOccurred to know when a person has been timed out in chat by a mod.  Is this the correct event to use?  In my testing I have not seen this event fire when a user has been timed out in the chat channel.

**Comment by SaviorXTanren** [comment]
According to the documentation, it's supposed to, but I agree that I personally have never seen the event fire. For reference, here is the Chat Client documentation; scroll down towards the bottom and you'll find a the "UserTimeout" event header: https://dev.mixer.com/reference/chat/index.html

I'll try taking a look into this closer when I get a chance and see if I can figure out what's going on.

**Comment by mphacker** [comment]
I figured out what was going on.  I was thinking the event would fire to all mods or stream owner when a person is timed out.  That isn’t the case.  It only fires on the user’s side.

On a somewhat related note,  I have noticed that from time to time when calling the ChatClient.Connect() method something gets hung up and the OnDisconnectOccured event starts firing off like crazy.   I am still trying to figure this out, but it seems to happen at least a couple times a day for me.  If I figure out what is going on, I will let you know.

One last question.   Any thoughts on how to address an issue where the chatclient seems to get disconnected from chat but the OnDisconnectOccured didn’t fire?  It seems like the client still thinks it is connect even though none of the chat message events are firing.

Thanks for an amazing library!  This has really helped out a ton.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by SaviorXTanren** [comment]
Ahh, that makes a bit more sense, but seems odd though that it wouldn't fire for everyone with at least moderator level access. :/

Your other two questions are probably be related to the Chat API issues that Mixer has been experiencing for the last 2 weeks. I've had a few conversations with the devs on https://gitter.im/Mixer/developers and given them what I've found so far. Essentially, the Chat API servers seems to run into some server issues, possibly related to congestion? They'll return back either 500 or 525 errors when this occurs and the only way to get around this is to simply keep attempting to connect until it works. Last update I have from the devs was on Monday saying that they've been able to re-produce the issue and are looking into it

**Comment by mphacker** [comment]
Hey there!

Quick question… does the chat client and constellation clients automatically handle the refreshing of the OAuth token or do I need to be tracking how long they have been signed in and calling a method to do the refresh?   It looks like in the docs the initial token expires in 6 hours so for long running streams or bot hanging in channels for long periods of time we need to refresh the token.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SaviorXTanren** [comment]
No, the clients themselves don't refresh the OAuth token, only the API connection itself. There's no good way to know from the clients (chat, constellation, interactive) when the API token will expire directly. Granted, I've never had a client connected for more than 6 hours to see what will happen. My guess is either nothing or it will just become disconnected, in which point you'd just want to listen for the disconnect event and re-establish it, which will automatically use whatever the latest version of the OAuth token is.

**Comment by mphacker** [comment]
Thanks!  I have had a few streams that lasted over 9 hours… I noticed that my code stopped really working and figured it was probably a OAUTH token expiration. After looking at the Mixer OAUTH docs it looks like it is set for 6 hours.  I will just track the time when the original connection occurs and then do a refresh of the token once 5 hours has passed.  I think that  should solve that issue.

I am still trying to figure out how to best handled the situation I mentioned to you where Mixer fails with an error during authentication.  When the issue happens it seems to cause the ChatClient OnDisconnectOccured event to just fire out of control.   I have tried wrapping the ChatClient.Connect method with a Try/Catch block but no exceptions seem to bubble up.  It just immediately jumps to the OnDisconnectOccured method and loops until I kill the process.

The crazy thing is that in the OnDisconnectOccured method I have even tried disposing of the ChatClient and setting it to null so that the loop issue doesn’t occur, but for some reason the OnDisconnectOccured just keeps firing.

When using the ChatClient, how are you capturing the exception when Mixer fails to connect in order to prevent this OnDisconnectOccured loop?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by SaviorXTanren** [comment]
Do you have any sort of timeout in your re connection logic? I add a 2 second timeout before I reconnect and I do the same as you, re-create the ChatClient from the ChatClient.CreateFromChannel() method. Mixer's continuing to have issues over the last month (Chat borked hard about an hour ago), so it's hard to diagnose most of the problems that I've been seeing lately.

**Comment by mphacker** [comment]
Mixer API has been a complete mess tonight. Constellation is not sending updates or there really late.  I know it's the API because updates are not even happening correctly on the mixer website.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
