### ISSUE TITLE
MixItUp "Unable to authenticate with Mixer"

### ISSUE THREAD

**Issue by CoffeeXXXX** [SaviorXTanren/mixer-client-csharp#20]
The application doesn't seem to like my browser or something... I did the approval on the pop-up page but it comes up with an error "Unable to authenticate with Mixer". Perhaps the servers are to take the blame? Or the application connectivity with Chrome? And Chrome itself says "Logged in successfully"  but MixItUp says otherwise... O.o

**Comment by SaviorXTanren** [comment]
The Mixer Chat APIs have been borked for the last 2 weeks, which has been causing connectivity issues.
