### ISSUE TITLE
RuntimeBinderException

### ISSUE THREAD

**Issue by xlxAciDxlx** [SaviorXTanren/mixer-client-csharp#21]
```c#
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at Mixer.Base.Clients.WebSocketClientBase.<ReceiveInternal>d__43.MoveNext()
```

**Comment by SaviorXTanren** [comment]
Do you have any more information about this bug? There's not really much to go off of here.

**Comment by xlxAciDxlx** [comment]
Unfortunately, I do not. It happened in the middle of the night (~3AM according to my logs), and there's no clear indication of _what_ caused it - no logged messages before or after that lead me to suspect what could've gone wrong.

I'll keep my bot running and update this in the event that I can figure out what may have caused it.

**Comment by SaviorXTanren** [comment]
Cool, mainly just need to get a line number out of it, as it could be a lot of things that could be triggering this exception.

**Comment by xlxAciDxlx** [comment]
Yeah, unfortunately, it hasn't happened again (yet) and the exception that did occur only showed what I had posted above.

**Comment by xlxAciDxlx** [comment]
Unfortunately, it occurred 3 more times in the middle of the night. Is there any way for me to try to track down _what_ is causing this?

**Comment by SaviorXTanren** [comment]
Well, a runtime binding exception is typically when a binding dependency doesn't exist (EX: we're casting to a type that doesn't exist or the depend binary that contains that type doesn't exist)

Here's a few questions to answer and something you could try:

- What OS are you running this on?
- What are you building this against? .NET or Mono and what version?

If you pull the latest source code, you could stick a try-catch inside the Receive() method and log the exception out to a file, then re-throw it so you'll know when the crash occurs.

**Comment by xlxAciDxlx** [comment]
I'm on Windows 10, building against .NET 4.6.1.

**Comment by xlxAciDxlx** [comment]
Alrighty, I'm going to close this for now as it _appears_ this is/was my fault. I added some more logging, and it appears anytime I get disconnected from my Constellation Client and try to reconnect, this error occurs.

If I find anything outside of that scope I'll reopen this and update you.

**Comment by SaviorXTanren** [comment]
@xlxAciDxlx How are you reconnecting? Are you calling Disconnect() then Connect() or are you just calling Connect()?

**Comment by xlxAciDxlx** [comment]
I'm calling `Disconnect()` and then `Connect()`.. I think I might need to refactor the Constellation Client portion of my code, as that's definitely where this is occurring. I just can't pinpoint the exact spot where it's happening.

**Comment by SaviorXTanren** [comment]
For whatever help it might be, here is the code I use in Mix It Up that wraps around the Constellation client, which handles re-connection. Hopefully it might help:

https://github.com/SaviorXTanren/mixer-mixitup/blob/master/MixItUp.Base/MixerAPI/ConstellationClientWrapper.cs
