### ISSUE TITLE
Feature Request - GET /channels/{channelIdOrToken}/details

### ISSUE THREAD

**Issue by Vyr1s** [SaviorXTanren/mixer-client-csharp#23]
Be nice to be able to access the extended sub information found at; channels/{channelIdOrToken}/details

numSubscribers:  uint
The current amount of subscribers the channel has.

maxConcurrentSubscribers:  uint
The maximum amount of concurrent subscribers.

totalUniqueSubscribers:  uint
The total amount of unique subscribers the user has had.

**Comment by SaviorXTanren** [comment]
Sorry about the delay on this one, just got back from a week-long business trip.
