### ISSUE TITLE
500 and 520 errors when using Short Code for authentication

### ISSUE THREAD

**Issue by kef95** [SaviorXTanren/mixer-client-csharp#24]
Short code authentication works once, and fails so many times that it's basically impractical to use it. Any idea why?

EDIT: To be specific, the code is thrown at `ChatClient.Connect()` method. Other than that it works as intended

**Comment by SaviorXTanren** [comment]
This is a Mixer-side issue unfortunately, it's been happening for the last month or two. It's also not specific to short code authentication, it'll occur using standard OAuth as well. You'll see either a 500, 520, or 525 error.

I've reported it to the Mixer devs multiple times, but they haven't seem to come up with a solution to it. Our current guess is this is related to the Spectre & Meltdown vulnerability updates that were deployed out to Azure, which could be causing some CPU over usage that the Mixer web services are not accounting for.

While they still attempt to figure out what's going on, my simple work around has been to disconnect, delay 1000 milliseconds, then re-connect. Sometimes it works on the first try, sometimes it takes a few. I've rarely seen it take more than 5 at most though.

**Comment by kef95** [comment]
Which part to retry exactly? Just the connecting to chat part or authorization as well?

**Comment by SaviorXTanren** [comment]
Just the Chat Client connection. Of all the web sockets connections, only Chat has these issues.

**Comment by kef95** [comment]
Thank you. That should do it
