### ISSUE TITLE
[Question] RestServiceRequestException

### ISSUE THREAD

**Issue by xlxAciDxlx** [SaviorXTanren/mixer-client-csharp#25]
When this exception is received with the message of "Not Found", does this mean that URI/URL isn't found, or the requested resource isn't found? For example, I received this calling `MixerConnection.Users.GetUser()`

**Comment by SaviorXTanren** [comment]
A 404 response should mean the user was not found. Did you use a username you expected to find?

**Comment by xlxAciDxlx** [comment]
Yes, I did, as it was getting the username of when someone was hosted. I added some more checks before/after the method call though, so hopefully, it won't happen again. I'll reopen this if it does.

**Comment by xlxAciDxlx** [comment]
Alright, I can confirm this every time with the following code.

```c#
if (payloadData.GetValue("hosteeId") == null)
{
	return;
}

this.Logger.Info("Processing payload data for \"hosteeId\"..");

uint hosteeId = (payloadData.GetValue("hosteeId") != null) ? (uint)payloadData.GetValue("hosteeId") : 0;
if (hosteeId == 0)
{
	return;
}

this.Logger.Info("Host Recipient ID: " + hosteeId);
try
{
	UserWithChannelModel hostRecipient = await this.Connection.Users.GetUser(hosteeId);

	if (hostRecipient != null)
	{
		this.SendMessage("We're now hosting @" + hostRecipient.username + "! Go drop them a follow and show them that Mixer love! https://mixer.com/" + hostRecipient.username);
	}
}
catch (Exception exception)
{
	this.Logger.Error("Unable to get user - " + exception);
}
```

**Comment by SaviorXTanren** [comment]
Where are you getting the hosteeId from, I'm assuming from a Constellation hosted event? If that ID is the channel ID, it won't work on the user's API, you'll need to query for the channel first, then get the user from that. For example:

https://dev.mixer.com/reference/constellation/index.html#example_channel__id__hosted

That returns the id of the channel that hosted, not the user account of the id. If you look at the payload that's returned, there's a "userId" property that you should be using instead:

  "hoster": {
    "featured": false,
    "id": 588,
    "userId": 696,
     ....
   }

**Comment by xlxAciDxlx** [comment]
I'm working on the implementation of when a channel (say mine) hosts another, not when a host is received to my channel.

**Comment by SaviorXTanren** [comment]
So here's my suggestion:

1. Use the "channel:{id}:update" Constellation event on your channel (The one that is hosting). Note that this event ONLY tells you what's changed, it will not have the entire channel object: https://dev.mixer.com/reference/constellation/index.html#events_live_events

2. Listen for when the "hosteeId" value on the Channel is changed: https://dev.mixer.com/rest.html#Channel

3. Call the API connection.Channels.GetChannel( hosteeId ) for the channel that you hosted. Just updated the nuget package to add this method, give it a few minutes to propagate though nuget's servers.

**Comment by xlxAciDxlx** [comment]
Any clue how it would not return the proper channel? For example, I hosted a channel and it didn't return the proper channel in the host message (from my bot).

**Comment by SaviorXTanren** [comment]
Yep, the naming conventions for their APIs can be a bit confusing :) I'll close the issue down, but feel free to open it again if you have any issues.

**Comment by xlxAciDxlx** [comment]
Thank you very much for all your help and quick responses, I appreciate it!
