### ISSUE TITLE
Interactive Disconnect Event Unknown

### ISSUE THREAD

**Issue by xlxAciDxlx** [SaviorXTanren/mixer-client-csharp#28]
When subscribing to the Interactive Disconnect event, I get this error (note *{channel_id}* is the redacted channel ID):
```txt
Packet Received: {"id":654341265,"type":"reply","result":null,"error":{"code":4106,"message":"Unknown event \"interactive:{channel_id}:disconnected\""}
```

Subscribing to the event as follows:
```c#
new ConstellationEventType(ConstellationEventTypeEnum.interactive__id__disconnected, this.Channel.id)
```

**Comment by SaviorXTanren** [comment]
So, good catch on this one. It was a naming issue ("disconnected" vs "disconnect"). However, as a further point, I actually can't get this or the connect events to be sent to me. Have a messaged out to the Mixer devs for further info about this.

**Comment by xlxAciDxlx** [comment]
Yeah, I figured it was just a naming issue as I know the event is `interactive:channelid:disconnect` (cross-referenced on the API docs to be sure). Also, I'll test events being sent once I update again. Currently waiting to test the auto-reconnect feature :D

**Comment by SaviorXTanren** [comment]
Nuget package with this update was just published:

https://www.nuget.org/packages/mixer-client-csharp/0.6.0.5-beta

**Comment by xlxAciDxlx** [comment]
Awesome! Thank you very much, again, for your hard work :D

**Comment by SaviorXTanren** [comment]
From discussion on the developer gitter:

> They've been removed in September last year, along with the channel:{id}:live events, if I'm not mistaken, with the suggestion to use channel:{id}:update instead, watching for changes of the online and interactive properties on the Channel you are monitoring.

**Comment by xlxAciDxlx** [comment]
That actually makes sense, given that `interactive (bool)` and `interactiveGameId (uint?)` exist within the Channel Model. Good to know, thanks :D
