### ISSUE TITLE
Possible memory leak with Constellation client

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/mixer-client-csharp#30]
When using the ConstellationClient I have been seeing excessive memory utilization which gets worse over time and eventually causes the client to stop receiving new constellation events.   When I comment out the code that creates the constellation client my code runs fine and stays under 100MB of memory consumption.  If I enable the code that creates the ConstellationClient I notice that over the next several minutes the memory utilization goes up until it is consuming close to 2GB of memory.  Once it hits a high memory usage level the constellation OnSubscribedEventOccurred stops firing.

It seems like after about 3 minutes of the code running I see the memory utilization jump to the 300MB mark and by 4 minutes it is pushing 500MB+.   After 5 minutes I am seeing it jump to over 1GB of memory but then GC kicks in and it drops to 500.  Sometime during this memory issue the constellation OnSubscribedTeventOccurred no longer fires.

I create the ConstellationClient after the ChatClient has connected and I have called the  ChatClient.Authenticate method.  I wire up the OnSubscribedEventOccurred and the OnDisconnectOccurred events and then if the ConstellationClient connects I call SubscribeToEvents.

I have been trying to track down the specific situation where the memory starts going out of control, but so far the only thing I have been able to identify is that if I don't use the ConstellationClient I don't see the memory usage issue. 

Any thoughts?

**Comment by mphacker** [comment]
I was able to reproduce the issue just by adding the constellation code to the sample console app.

**Comment by mphacker** [comment]
Rolled back to version 0.5.2.8-beta and have been running my test for 7 minutes now with constellation events enabled and I am not seeing any memory issues at all.   I tried version 0.6.0.4-beta and ran into the issue.  So it appears something was introduced that is not releasing memory in the newer builds.  Still trying to track down more info.

**Comment by mphacker** [comment]
I think I have a fix.  I am going to do some more testing tonight.  If it works well I will submit it.

**Comment by SaviorXTanren** [comment]
Hey, sorry for the delay response, I've been on a business trip for the last week.

Buffer length shouldn't be a concern, if Mixer is sending individual packets that are larger than 1 MB, there's a bigger problem. :)

The WebSocketBase is already in a loop and reading until an end of message is received. You're code does the same thing effectively, though you're simply writing the ReceiveAsync result to a MemoryStream with every receive, but not doing a full check on the contents of the received packet or if the socket has been closed.

If you look at the code segment link below, you'll see we're appending the contents to a string buffer, then doing an EndOfMessage check after every received packet:

https://github.com/SaviorXTanren/mixer-client-csharp/blob/e2011fdfe043d923f1b87bf66609e43bb7d0ab8f/Mixer.Base/Web/WebSocketBase.cs#L108-L143

Now, there could be some wonky corner case I'm not seeing, though the error that the JSON parsing is complaining about seems more relative to the contents of the packet. In your first failure example, it complains about not being able to parse "data.payload.following", but if you notice, that field isn't even present in the JSON. If anything, it should have complained about parsing "data.payload.user.channel", as that's where the fragment falls apart in that JSON example.

It's entirely possible something has also changed in the JSON that Mixer returns (it's happened a fair amount without warning). Let me look into this further and see what I can find out.

**Comment by SaviorXTanren** [comment]
Commit c179813 has some quality of life improvements overall to the WebSocketBase Receive() method based on a few things from your suggestions, though overall SHOULDN'T have changed anything that should affect this issue. I'll dig into the JSON format more and see if they changed anything for it, though I'm not seeing any exceptions when using your sample edits to the Console app.

**Comment by mphacker** [comment]
I just pulled the latest into my project. Going to do some tests to see if I run into any packet errors.  Thanks!

**Comment by mphacker** [comment]
This issue appears to be resolved.
