### ISSUE TITLE
Why do I need a refreshToken if set to false?

### ISSUE THREAD

**Issue by D3thw0lf** [SaviorXTanren/mixer-client-csharp#31]
Since the latest Updates (0.6 >) it seems like the "OAuthTokenModel" now needs a refreshToken even if I set it to false on "ConnectViaOAuthToken". 

So my question(s) is/are: Is this a bug or is the ability to set it to false now deprecated? Did I maybe missed something? As always thanks for the great work on this lib. 👍 :)

**Comment by SaviorXTanren** [comment]
What do you mean by it "needs" a refresh token? Whenever you get a token for ConnectViaOAuthToken(), you will always get a refresh token value assigned to the OAuthTokenModel, that's just the way it works.

**Comment by D3thw0lf** [comment]
I get this error while trying to connect the way it worked versions before 0.6 or higher
> 2018-04-21 12:00:16.4406 TRACE https://mixer.com/api/v1/oauth/token
> {"details":[{"message":"\"refresh_token\" must be a string","path":["refresh_token"],"type":"string.base","context":{"value":null,"key":"refresh_token","label":"refresh_token"}}],"isJoi":true,"name":"ValidationError"}
> Mixer.Base.Util.RestServiceRequestException: Bad Request
This is the error I get.

Code I use for Auth:
```c
var token = new OAuthTokenModel { clientID = "MyClientID", accessToken = AppSettings.OAuthToken };
connection = await MixerConnection.ConnectViaOAuthToken(token, false);
