### ISSUE TITLE
Need "error" response from chatclient

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/mixer-client-csharp#32]
It appears that the response object from the ChatClient SendWithResponse and WhisperWithResponse does not include "error".   Isn't this needed in order to verify that a message was actually sent and not lost due to rate limiting or other issues?

**Comment by SaviorXTanren** [comment]
The error response is checked automatically whenever a "_____WithResponse" method is called. If there is any error detected, we throw a ReplyPacketException exception from the method to let you know what went wrong:

https://github.com/SaviorXTanren/mixer-client-csharp/blob/master/Mixer.Base/Clients/MixerWebSocketClientBase.cs#L173-L184

**Comment by mphacker** [comment]
Thanks!  Missed that when looking through the code.  Thank you for the quick response!
