### ISSUE TITLE
ConnectViaLocalHostOAuthBrowser method does not force approval prompt

### ISSUE THREAD

**Issue by goblix** [SaviorXTanren/mixer-client-csharp#36]
`MixerConnection connection = await MixerConnection.ConnectViaLocalhostOAuthBrowser(clientID, scopes, true);
`

Hi as per the code above the third option in the method is to force approval prompt but regardless of setting it to true it does not seem to force the prompt.

upon looking at the resulting Mixer authorize url string it doesn't look like it is building the "approval_prompt=force" within the url

**Comment by SaviorXTanren** [comment]
Good catch! We we're passing the value in to the 2nd overload of the function.
