### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by jaguillard** [SaviorXTanren/mixer-client-csharp#39]
Currently when using:

MixerBase.Clients.ChatClient.Connect.Wait()

I am getting an exception:

"The WebSocket protocol is not supported on this platform."

A brief googling seems to indicate that Microsoft has no plans to implement WebSockets on anything older than Windows 8.  Is there a current workaround to get the API working on Windows 7?  

I did not notice anything about platform support in the Readme docs, so I apologize if this is covered somewhere I missed.

**Comment by SaviorXTanren** [comment]
Correct, the native WebSocket support was only added in Windows 8 and up. I don't have any plans as of right now to move our WebSocket code over to another library, but you could branch the project and switch it over to another WebSocket library; WebSocketSharp is a fairly good one from what I've heard:

https://www.nuget.org/packages/WebSocketSharp/1.0.3-rc11

It might take a little bit of work, but luckily most of the WebSocket logic is contained only in a few classes.

**Comment by amirvenus** [comment]
Is there a possibility to run this on macOS?

**Comment by SaviorXTanren** [comment]
No, .NET Framework 2.0 doesn't support Mac compilation. Eventually if we decide to port this over to .NET Core, that would be possible.
