### ISSUE TITLE
[Question] Setting up OAuth

### ISSUE THREAD

**Issue by RainbowCookie32** [SaviorXTanren/mixer-client-csharp#54]
Sorry if it's not strictly related to this project, or if I shouldn't post it here but I couldn't really find much relevant info on other places.

If I use the ClientID provided on ChatSample.WPF, everything works perfectly as expected. But the moment I change it to my ID I get `"There was an error in your OAuth request. This is probably an issue with the site you just came from, not Mixer. Contact them to resolve this error. Error details for developers: The redirect uri is invalid."`.

I'm pretty sure the problem is on my OAuth application on Mixer, so here's my question. How should I set it up for using it with for example the ChatSample.WPF sample? What should I set as Website and/or Hosts on Mixer?

Sorry again if I shouldn't post this here.

**Comment by SaviorXTanren** [comment]
It depends highly on how you configured your OAuth application on Mixer. Did you enable a client secret? What did you set for your redirect URL? For the sample applications, there's no secret and these are the settings that it is using:

![image](https://user-images.githubusercontent.com/752903/52999519-e044c080-33da-11e9-9fb5-c4190dc40c8a.png)

**Comment by RainbowCookie32** [comment]
> It depends highly on how you configured your OAuth application on Mixer. Did you enable a client secret? What did you set for your redirect URL? For the sample applications, there's no secret and these are the settings that it is using:
> 
> ![image](https://user-images.githubusercontent.com/752903/52999519-e044c080-33da-11e9-9fb5-c4190dc40c8a.png)

That was just the reference picture I needed. Thank you very much, I'll be closing the issue. Really cool project you have here!

**Comment by RainbowCookie32** [comment]
Here I come again. I'm now having issues using ConnectViaAuthorizationCode().

I'm doing some experimenting with a personal chat bot. What I wanted to do was: get the authorization code on the first run with ConnectViaLocalhostOAuthBrowser(), save it, and then just use ConnectViaAuthorizationCode() with the saved code. So I get the authcode with `connection.GetOAuthTokenCopy().authorizationCode`, save it to a file, then try to connect with `ConnectViaAuthorizationCode(myClientID, theAuthCode);` but when I run the program I get 

```
System.AggregateException
Inner Exception
RestServiceRequestException: Bad Request
```

I'm probably missing something, but I'm not quite sure what it is. Is it even possible to do what I want to do?

**Comment by SaviorXTanren** [comment]
The authorization code is a one-time thing that expires in 30 seconds or so, so you can't save that. You need to save the OAuthToken and use that to reconnect with using the MixerConnection.ConnectViaOAuthToken() method.

**Comment by RainbowCookie32** [comment]
> The authorization code is a one-time thing that expires in 30 seconds or so, so you can't save that. You need to save the OAuthToken and use that to reconnect with using the MixerConnection.ConnectViaOAuthToken() method.

That explains it, I'll probably rethink my approach a bit. Thank you very much
