### ISSUE TITLE
GetAuthorizationCodeURLForOAuthBrowser task does not complete

### ISSUE THREAD

**Issue by thoralmighty** [SaviorXTanren/mixer-client-csharp#56]
I'm using `GetAuthorizationCodeURLForOAuthBrowser` to retrieve an URL for displaying in a custom web browser, but recently the following line started hanging indefinitely:
`string url = MixerConnection.GetAuthorizationCodeURLForOAuthBrowser(clientID, clientSecret, scopes, callbackUrl).Result;`

This also occurs if I omit `clientSecret`, and a breakpoint on the next line is never reached.
I've let it go for several minutes so it doesn't seem to hit any sort of timeout, and I've also checked that the ID, secret and callbackURL are correct and/or not null.

The application doesn't freeze but it sits idle, as if waiting for an API response maybe?

Any suggestions on this?

**Comment by thoralmighty** [comment]
Looks like this was a problem with how I was handling the asynchronous call, resolved by `await`ing it and changing the enclosing method to async. I still find it strange how it hasn't stopped like that before though, I definitely thought I had already tried this solution. I'm still learning some aspects of asynchronous programming after all, it sure is convenient albeit a little confusing.

```public async void Connect()
{
    //...
    string url = await MixerConnection.GetAuthorizationCodeURLForOAuthBrowser(clientID, clientSecret, scopes, callbackUrl);
}```

**Comment by SpaceShot** [comment]
Blocking on Result can deadlock in some seemingly innocuous situations. I'm not great at spotting it even in larger blocks of code, but generally if you can go with await in those situations you should be happier.
