### ISSUE TITLE
Spark transactions not being captured.

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/mixer-client-csharp#61]
Has anyone experienced issues recently with spark transactions not being captured even though the CaptureSparkTransactionWithResponse method returns true?   Using V1 version of the client software.   Experienced it even with the original client build too.  Everything was working fine until earlier this week.   Thinking it might be a Mixer issue but need to do more debugging this weekend to 100% verify that the API is showing the transaction was captured.

**Comment by SaviorXTanren** [comment]
We've seen some sporadic cases of this as well, but haven't been able to pin it down to anything. We do that sometimes certain MixPlay servers can be having issues more than others, but we wouldn't even know which one was if that was the case currently.

**Comment by mphacker** [comment]
I have had lots of issues this past week. I did open a support ticket with Mixer, but they are really bad at actually telling you if there is a problem and if / when it is fixed.

**Comment by mphacker** [comment]
Looks like things are back to working tonight in the channel where my app runs.
