### ISSUE TITLE
Authenticate without OAuth Server

### ISSUE THREAD

**Issue by TheOfficialLoren** [SaviorXTanren/mixer-client-csharp#63]
Hello,
  I have been poking around the Mixer client and am trying to find a way to authenticate without the OAuth server. I have a bot that will be containerized and run remotely without user interaction. I'm hoping there's a way that I can autheticate with a bot account using stream key. Is that possible with the client?

**Comment by TyrenDe** [comment]
I understand what you are asking, but the process of OAuth requires user interaction, for security reasons.  It is possible to generate a token once, and refresh/reuse that token for a long time. If the refresh fails or expires, it will require recreating a new token with user interaction again.  Does that make sense?

Using the shortcode method could allow you to perform that refresh remotely if you could have your service notify you that it needs a refresh... send the code/link to you to perform it remotely/manually. Then you could get an OAuth token that way.  Hope that helps.

**Comment by TheOfficialLoren** [comment]
@TyrenDe  Thank you for the answer!

So what would the workflow look like?

I'd run the OAuth browser authentication and I'd retrieve the auth code from the connection response? And then the next time I kick up the task I'd `MixerConnection.ConnectViaAuthorizationCode()`? I tried doing that and got an error stating that the auth code was already used.

**Comment by TyrenDe** [comment]
I wrote you a detailed e-mail. Let's chat there. :)
