### ISSUE TITLE
Master vs. v1Changes?

### ISSUE THREAD

**Issue by sushihangover** [SaviorXTanren/mixer-client-csharp#65]
Are the sole differences between the two branches the addition of YT and Twitch support? Any roadmap of what v1Changes will be?

Thanks, Robert

**Comment by SaviorXTanren** [comment]
v1Changes contains several updates and breaking changes to the Mixer libraries, in addition to adding similarly structured libraries for YouTube & Twitch. It's our opportunity to work on finalizing the library for a 1.0 release without breaking current users. Most of the work in the v1Changes branch has been completed, we are simply proofing & validating things before we are ready to push them to master.

**Comment by sushihangover** [comment]
@SaviorXTanren Thanks for the info. -Robert
