### ISSUE TITLE
NuGet Package?

### ISSUE THREAD

**Issue by ChrisVollink** [SaviorXTanren/mixer-client-csharp#8]
Are there any plans to add a nugget package for easy installation of your library?

**Comment by SaviorXTanren** [comment]
Yes, I would love to add nuget support at some point. I'm waiting until the API becomes a bit more stable to do that, hoping sometime by the end of this year.

**Comment by ChrisVollink** [comment]
Good to hear! Thanks for bringing such a great client library to C#. I was originally disheartened to only see a Unity plugin from Mixer.

**Comment by SaviorXTanren** [comment]
Let's keep this issue open until I do it, just as a reminder to me.

_Sent from my Motorola Moto G (5) Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by D3thw0lf** [comment]
Uh this answers my question from the Forums at mixer. :)

**Comment by SaviorXTanren** [comment]
Nuget package has been created. Currently putting it as a beta until I finalize a few more things and complete the documentation, but have at it!

https://www.nuget.org/packages/mixer-client-csharp
